<a href="https://colab.research.google.com/github/Advait177013/ML_CSE4020/blob/main/Numpy_online_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [4]:
arr1=numpy.array([20, 11, 43])
print(arr1)
arr2=numpy.array([[2, 0], [1, 1], [4, 3]])
print(arr2)

[20 11 43]
[[2 0]
 [1 1]
 [4 3]]


In [5]:
print(type(arr2))
print(arr2.dtype)
print(arr2.shape)
print(arr2.size)
print(arr2.itemsize)
print(arr2.ndim)
print(arr2.nbytes)

<class 'numpy.ndarray'>
int64
(3, 2)
6
8
2
48


In [7]:
arr_zer=numpy.zeros((3, 3), dtype=float)
arr_ones=numpy.ones((3, 3), dtype=int)
arr_iden=numpy.eye(3, 4)
arr_rand=numpy.random.rand(2, 5)
arr_randint=numpy.random.randint(2, size=(4, 4))
print(arr_zer)
print(arr_ones)
print(arr_iden)
print(arr_rand)
print(arr_randint)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0.27044619 0.5132273  0.3208573  0.48191246 0.1700705 ]
 [0.66779112 0.07278576 0.74240294 0.96149947 0.57183305]]
[[0 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]]


In [9]:
arr_arr=numpy.arange(0, 69, 23)
print(arr_arr)

[ 0 23 46]


In [10]:
arr_lin=numpy.linspace(0, 10, 11)
print(arr_lin)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
print(arr_rand, "\n")
print(arr_rand[:2], "\n")
print(arr_rand[1:], "\n")
print(arr_rand[0:1, 2:4], "\n")
print(arr_rand[:], "\n")
print(arr_rand[:,1::3], "\n")

[[0.27044619 0.5132273  0.3208573  0.48191246 0.1700705 ]
 [0.66779112 0.07278576 0.74240294 0.96149947 0.57183305]] 

[[0.27044619 0.5132273  0.3208573  0.48191246 0.1700705 ]
 [0.66779112 0.07278576 0.74240294 0.96149947 0.57183305]] 

[[0.66779112 0.07278576 0.74240294 0.96149947 0.57183305]] 

[[0.3208573  0.48191246]] 

[[0.27044619 0.5132273  0.3208573  0.48191246 0.1700705 ]
 [0.66779112 0.07278576 0.74240294 0.96149947 0.57183305]] 

[[0.5132273  0.1700705 ]
 [0.07278576 0.57183305]] 



In [20]:
arr20=numpy.array([0x000000, 0xA322EF, 0x2AFF00, 0x345AAA, 0x123456, 0xFFFFFF])
mask=numpy.array([1, 0, 1, 0, 0, 1], dtype=bool)
print(arr20[mask])

[       0  2817792 16777215]


In [29]:
arr21=numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr21)
print("sum\t:", numpy.sum(arr21))
print("sum\t:", numpy.sum(arr21, axis=1))
print("prod\t:", numpy.prod(arr21))
print("prod\t:", numpy.prod(arr21, axis=0))
print("min\t:", numpy.min(arr21))
print("max\t:", numpy.max(arr21))
print("min\t:", numpy.min(arr21, axis=0))
print("max\t:", numpy.max(arr21, axis=1))
print("mean\t:", numpy.mean(arr21, axis=0))
print("var\t:", numpy.var(arr21, axis=0))
print("std dev\t:", numpy.std(arr21, axis=0))
print("avg\t:", numpy.average(arr21, axis=1))
print("wgt avg\t:", numpy.average(arr21, weights=[2, 1, 2], axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum	: 45
sum	: [ 6 15 24]
prod	: 362880
prod	: [ 28  80 162]
min	: 1
max	: 9
min	: [1 2 3]
max	: [3 6 9]
mean	: [4. 5. 6.]
var	: [6. 6. 6.]
std dev	: [2.44948974 2.44948974 2.44948974]
avg	: [2. 5. 8.]
wgt avg	: [2. 5. 8.]


In [39]:
print(arr21[2]+arr21[0])
print(arr21[2]-arr21[0])
print(arr21[2]+5)

[ 8 10 12]
[6 6 6]
[12 13 14]


In [42]:
print(arr21[0]==arr21[1])
print(arr21[0][1]>arr21[0][2])
print(arr21[0][1]<arr21[2])

[False False False]
False
[ True  True  True]


In [52]:
print("sine of pi radians : ", numpy.sin(numpy.pi))
print("cosian of pi/4 : ", numpy.cos((numpy.pi/4)))
print("natural log of e: ", numpy.log(numpy.e))
print("natural log of 10: ", numpy.log(10))

sine of pi radians :  1.2246467991473532e-16
cosian of pi/4 :  0.7071067811865476
natural log of e:  1.0
natural log of 10:  2.302585092994046


In [53]:
a1=numpy.array([1, 2, 4, 8, 16])
a2=numpy.array([1, 1, 2, 3, 5])
print(a1)
print(a2)
print(numpy.add(a1, 2))
print(numpy.subtract(a2, 2))
print(numpy.multiply(a1, 2))
print(numpy.divide(a2, 2))
print(numpy.power(a1, 2))

[ 1  2  4  8 16]
[1 1 2 3 5]
[ 3  4  6 10 18]
[-1 -1  0  1  3]
[ 2  4  8 16 32]
[0.5 0.5 1.  1.5 2.5]
[  1   4  16  64 256]


In [55]:
import numpy as np
print(np.add(a1, a2))
print(np.subtract(a1, a2))
print(np.divide(a1, a2))
print(np.power(a1, a2))
print(np.array_equal(a1, a2))
print(np.sqrt(a1))
print(np.round(a2))

[ 2  3  6 11 21]
[ 0  1  2  5 11]
[1.         2.         2.         2.66666667 3.2       ]
[      1       2      16     512 1048576]
False
[1.         1.41421356 2.         2.82842712 4.        ]
[1 1 2 3 5]


In [63]:
print(np.mean(arr21))
print(np.mean(arr21, axis=1))
print(np.sum(arr21))
print(np.sum(arr21, axis=1))
print(np.var(arr21))
print(np.std(arr21))
print(np.corrcoef(arr21))

5.0
[2. 5. 8.]
45
[ 6 15 24]
6.666666666666667
2.581988897471611
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
